
import { createContext, useState } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export const Store = createContext();


export default function RootLayout({ children }) {

    const[user,setUser]= useState({});
    const [chatUser,setChatUser] =useState([])






  return (
    <html lang="en">
      <body className={inter.className}>
        <Store.Provider value={{user,setUser,chatUser,setChatUser}}>
        {children}
        </Store.Provider>
      </body>
    </html>
  )
}
